import { useEffect, useMemo, useState } from "react";
import { Link, NavLink, Route, Routes, useLocation } from "react-router-dom";
import "./index.css";

const BRAND = {
  name: "ClickBoost Media",
  tagline: "Precision Marketing. Measurable Growth. Global Reach.",
  subTagline: "Dedicated specialists. Proven results. Your unfair competitive advantage.",
  email: "info@clickboostmedia.com",
  phone: "+1-XXX-XXX-XXXX",
  address: "[US Office Address — To Be Confirmed]",
  site: "https://www.clickboostmedia.com",
};

const primaryCta = `mailto:${BRAND.email}?subject=Free Consultation Request`;
const auditCta = `mailto:${BRAND.email}?subject=Free Website Audit Request`;

const services = [
  {
    slug: "seo",
    short: "SEO",
    title: "SEO Services That Put You on Page One — And Keep You There",
    nav: "SEO Services",
    desc: "Sustainable SEO services for technical fixes, content strategy, authority building, local search, and AI-era visibility.",
    icon: "⌁",
    overview: "On-page, off-page, technical, local, AI/GEO optimization",
    intro: "Search engine optimization isn't a one-time fix — it's a discipline. At ClickBoost Media, our dedicated SEO team combines technical precision, content strategy, and authority building to deliver sustainable, compounding organic growth for your business. Whether you're a local business in Dallas trying to dominate your neighborhood or a SaaS company in San Francisco targeting national keywords, we build SEO strategies that align with your business goals, your audience, and the constantly shifting landscape of Google's algorithm. Our team has navigated every major Google update — Panda, Penguin, Hummingbird, BERT, Helpful Content, and the rise of AI Overviews — and emerged stronger each time because our approach has always prioritized genuine value over shortcuts. We map search intent, fix crawl and performance issues, publish content that answers real buyer questions, earn authority through ethical digital PR, and report the numbers that matter: rankings, qualified traffic, leads, and revenue influence. The result is not a temporary spike; it is a search engine presence that keeps working long after the first campaign sprint ends.",
    included: ["Technical SEO Audit & Fixes", "Keyword Research & Competitive Gap Analysis", "On-Page Optimization", "Content Strategy & SEO Copywriting", "Link Building & Digital PR", "Local SEO & Google Business Profile Optimization", "Generative Engine Optimization (GEO)", "Answer Engine Optimization (AEO)", "Monthly Reporting with rank tracking & traffic analysis"],
    process: ["Discovery", "Audit", "Strategy", "Implementation", "Link Building", "Monitor & Optimize", "Report"],
    tools: ["Google Search Console", "Ahrefs", "SEMrush", "Screaming Frog", "PageSpeed Insights", "Schema Pro"],
    faqs: [
      ["How long does SEO take to show results?", "Most clients see early technical and visibility improvements within 30–60 days, with stronger lead and ranking momentum typically building over 3–6 months."],
      ["Do you do link building?", "Yes. We focus on ethical authority building, digital PR, partnership outreach, and content-led link acquisition."],
      ["Can you help with local SEO for my US business?", "Yes. We optimize Google Business Profile, local landing pages, citations, reviews, and city-specific content for US markets."],
      ["What makes your SEO different from other agencies?", "We combine technical SEO, conversion psychology, content depth, and AI-era answer optimization instead of relying on generic checklists."],
    ],
  },
  {
    slug: "smo",
    short: "SMO",
    title: "Social Media Marketing That Builds Real Audiences, Not Just Followers",
    nav: "Social Media Marketing",
    desc: "Social media marketing services for content calendars, community management, paid social, and measurable audience growth.",
    icon: "◍",
    overview: "Strategy, content, community management, paid social",
    intro: "Social media marketing is no longer about posting more often and hoping the algorithm cooperates. It is about building trust at scale, understanding platform culture, and designing content systems that turn attention into qualified conversations. ClickBoost Media helps businesses create strategic social media programs across Facebook, Instagram, LinkedIn, Twitter/X, Pinterest, YouTube, and TikTok. Our dedicated social media team develops your voice, optimizes your profiles, maps audience segments, builds monthly content calendars, manages community interactions, tests hooks and creative formats, and tracks the complete path from reach to lead. For B2B brands, we emphasize LinkedIn thought leadership, authority-building posts, and outreach workflows that book meetings. For consumer brands, we build visual storytelling, short-form video concepts, paid social funnels, influencer outreach, and retargeting campaigns that make your offer impossible to ignore. Every post has a purpose, every campaign has a metric, and every reporting cycle includes clear next steps for stronger performance.",
    included: ["Profile optimization", "Content calendar planning", "Community management", "Hashtag and trend strategy", "Paid social campaigns", "Influencer outreach", "Creative testing", "Analytics reporting"],
    process: ["Audience Mapping", "Profile Audit", "Content System", "Creative Production", "Campaign Launch", "Community Response", "Optimization"],
    tools: ["Meta Business Suite", "LinkedIn Campaign Manager", "TikTok Ads", "YouTube Studio", "Canva", "Buffer", "Sprout Social"],
    faqs: [["Which platforms do you manage?", "We support Facebook, Instagram, LinkedIn, Twitter/X, Pinterest, YouTube, and TikTok strategy."], ["Do you create content?", "Yes. We create captions, creative briefs, graphics direction, short-form video concepts, and posting calendars."], ["Can social media generate leads?", "Yes, when it is paired with the right landing pages, retargeting, lead magnets, and sales follow-up."], ["Do you run paid social campaigns?", "Yes. We manage paid campaigns across Meta, LinkedIn, TikTok, and other relevant platforms."]],
  },
  {
    slug: "web-development",
    short: "Web Dev",
    title: "Custom Websites Engineered for Performance, Conversion, and Growth",
    nav: "Web Development",
    desc: "High-performance web development services for custom websites, WordPress, ecommerce, landing pages, and redesigns.",
    icon: "▣",
    overview: "Custom websites, WordPress, ecommerce, landing pages",
    intro: "Your website is not just a digital brochure; it is the operating system for your brand's growth. ClickBoost Media builds custom websites engineered for speed, clarity, conversion, and long-term maintainability. Our development team works closely with strategists, designers, SEO specialists, and content experts so every page is built with a business purpose. We handle WordPress development, custom HTML/CSS/JS, ecommerce experiences on WooCommerce and Shopify, high-converting landing pages, website redesigns, page-speed optimization, security hardening, analytics setup, and ongoing improvements. We think through navigation, content hierarchy, Core Web Vitals, schema, accessibility, lead capture, and mobile performance before a single page goes live. The result is a website that feels premium, loads quickly, earns trust, and supports measurable marketing outcomes. Whether you need a polished corporate site, a conversion-focused funnel, a marketplace, or a scalable ecommerce storefront, our dedicated team of experts can take your project from architecture to launch with clear communication and accountable delivery.",
    included: ["Custom website design and development", "WordPress and CMS builds", "WooCommerce and Shopify ecommerce", "Landing pages", "Website redesign", "Speed optimization", "Security hardening", "Analytics and conversion tracking"],
    process: ["Discovery", "Information Architecture", "UX/UI", "Development", "SEO Setup", "QA", "Launch"],
    tools: ["WordPress", "React", "Next.js", "PHP", "WooCommerce", "Shopify", "MySQL", "AWS"],
    faqs: [["Do you build WordPress websites?", "Yes. We build custom WordPress websites, landing pages, and ecommerce stores."], ["Can you redesign an existing site?", "Yes. We audit your current site, preserve what works, and rebuild what limits growth."], ["Do you optimize for speed?", "Yes. Performance and Core Web Vitals are core parts of our development process."], ["Can you support after launch?", "Yes. We offer monthly maintenance, analytics, content, and optimization support."]],
  },
  {
    slug: "app-development",
    short: "App Dev",
    title: "Mobile & Web Applications Built for Scale — From Concept to App Store",
    nav: "Application Development",
    desc: "Mobile and web application development services for iOS, Android, cross-platform apps, MVPs, UI/UX, and ASO.",
    icon: "▰",
    overview: "iOS, Android, cross-platform apps from concept to launch",
    intro: "Great applications solve painful problems with simple, reliable, and beautiful user experiences. ClickBoost Media helps founders and businesses turn app ideas into market-ready products through a disciplined development process. We support iOS apps with Swift, Android apps with Kotlin, cross-platform products with React Native and Flutter, modern web apps, MVP development, UI/UX design, app store optimization, analytics, and release planning. Our approach starts with feasibility, user flows, feature prioritization, and an MVP roadmap so budget is invested in the functionality that matters most. From there, we design clickable prototypes, build in sprints, test across devices, prepare launch assets, and help you learn from early user behavior. Whether you are building a productivity tool, fitness marketplace, dating product, SEO utility, restaurant discovery app, or business workflow platform, our globally distributed team of specialists brings product thinking, technical execution, and growth marketing context together under one accountable process. See our demo apps below to explore the range of products we can ship.",
    included: ["iOS app development", "Android app development", "React Native and Flutter", "Web app development", "MVP development", "UI/UX design", "App Store Optimization", "Analytics and launch support"],
    process: ["Idea Validation", "Feature Prioritization", "Wireframes", "Design", "Sprint Development", "QA", "App Store Launch"],
    tools: ["Swift", "Kotlin", "React Native", "Flutter", "Firebase", "Figma", "Node.js", "AWS"],
    faqs: [["Can you build an MVP first?", "Yes. We recommend an MVP for most new apps to validate demand before expanding features."], ["Do you handle App Store submission?", "Yes. We prepare app assets, metadata, testing, and submission workflows."], ["Can you build both mobile and web apps?", "Yes. We build native mobile, cross-platform mobile, and web applications."], ["Do you help with app marketing?", "Yes. We can support ASO, launch campaigns, SEO, paid media, and content strategy."]],
  },
  {
    slug: "content-marketing",
    short: "Content",
    title: "Content That Educates, Engages, and Converts Your Ideal Customers",
    nav: "Content Marketing",
    desc: "Content marketing services for blog strategy, website copy, email sequences, video scripts, whitepapers, and case studies.",
    icon: "✦",
    overview: "Blog strategy, copywriting, video scripts, email sequences",
    intro: "Content marketing works when it gives buyers the confidence to take the next step. ClickBoost Media creates content systems that educate your audience, demonstrate authority, and support every stage of the funnel. Our content team handles blog strategy, SEO copywriting, website messaging, email sequences, video scripts, whitepapers, case studies, social media content, content audits, and thought leadership programs. We begin by understanding your customer psychology: what motivates them, what objections hold them back, what search terms they use, what proof they need, and what tone earns trust. Then we create a content roadmap that blends keyword opportunity, buyer intent, competitive gaps, and brand differentiation. Every asset is written to be useful to humans, structured for search engines, and clear enough for sales teams to use in real conversations. Whether you need a full content engine or a focused set of conversion pages, we create the messaging foundation that makes SEO, social media, email, and paid campaigns work harder.",
    included: ["Blog writing", "Website copywriting", "Email marketing sequences", "Video scripts", "Whitepapers", "Case studies", "Social media content", "Content audits"],
    process: ["Audience Research", "Content Audit", "Roadmap", "Production", "Optimization", "Distribution", "Reporting"],
    tools: ["Google Analytics 4", "Search Console", "SurferSEO", "Grammarly", "Notion", "Canva", "HubSpot"],
    faqs: [["Do you write SEO blogs?", "Yes. We create SEO-focused blog content built around search intent and conversion goals."], ["Can you improve existing content?", "Yes. We audit, refresh, consolidate, and optimize existing content libraries."], ["Do you write email sequences?", "Yes. We write welcome, nurture, sales, reactivation, and newsletter sequences."], ["How do you measure content ROI?", "We track rankings, traffic quality, assisted conversions, lead quality, engagement, and sales enablement value."]],
  },
];

const blogPosts = [
  ["SEO", "How Google's AI Overviews Are Changing SEO in 2025 — And What to Do About It", "Google's AI-generated summaries now appear above traditional organic results for millions of queries. For businesses that have invested years in SEO, this shift feels threatening. But for those who understand the opportunity, it's actually the biggest visibility unlock since featured snippets. In this article, we break down exactly how AI Overviews select their sources, why E-E-A-T (Experience, Expertise, Authoritativeness, Trustworthiness) is now your single most important ranking signal, and the specific content structures that are most likely to get your website cited in AI responses. We'll also share a 5-step audit you can run today to identify your highest-opportunity pages, rewrite answer-ready sections, improve entity clarity, strengthen author signals, and create comparison content that earns visibility in both traditional rankings and AI-generated recommendations.", "7 min read"],
  ["SMO", "The Real Reason Your Social Media Isn't Converting (It's Not What You Think)", "Most businesses approach social media as a broadcast channel — they post content and wait for sales to arrive. But the businesses that actually convert social media followers into paying customers understand something fundamental: social media is a trust-building machine, not a sales machine. The selling happens on your website, in your DMs, on your sales calls — not in your Instagram feed. This article reveals the 4-stage social media conversion framework we use for our US clients, which consistently turns cold audiences into warm leads within 60-90 days. You'll learn how to align educational content, proof-based posts, community responses, retargeting audiences, and conversion pages so your social presence creates trust before prospects ever speak with your team.", "6 min read"],
  ["AI Marketing", "Why Smart Businesses Are Choosing Specialist Digital Marketing Agencies in 2025", "The full-service agency model is showing its cracks. When one agency claims to do everything equally well — SEO, paid ads, web development, content, social media, email marketing — something has to give. Smart businesses are increasingly choosing agencies with deep specialization in specific disciplines, or boutique full-service agencies where every discipline has a dedicated senior specialist rather than being handled by generalists. In this article, we examine why the 'one-stop-shop' promise often underdelivers and what to look for when evaluating your next agency partner. We cover team structure, reporting transparency, channel ownership, technical depth, strategic accountability, and the questions that reveal whether your agency partner can actually execute the growth plan they present.", "5 min read"],
  ["SEO", "Core Web Vitals in 2025: The Technical SEO Checklist That Actually Moves Rankings", "Google's Page Experience signals have matured from a theoretical ranking factor into a genuine differentiator — particularly in competitive verticals where top-10 pages are otherwise closely matched in content quality and authority. Our technical SEO team has audited over 200 websites and identified the 12 most impactful Core Web Vitals fixes, ranked by their measurable effect on both rankings and user behavior metrics. This isn't a generic checklist — every recommendation is backed by split-test data from real client websites. We cover image delivery, JavaScript reduction, server response times, layout stability, interaction latency, font loading, analytics scripts, theme bloat, mobile rendering, caching, CDN configuration, and the prioritization model that helps teams fix what matters first.", "8 min read"],
  ["App Dev", "Building an App in 2025: The MVP Approach That Saves Time, Money, and Heartbreak", "Most app projects fail not because the idea was bad, but because they tried to build too much, too fast, with too little user validation. The Minimum Viable Product methodology — when executed properly — is the single most reliable predictor of app success. In this article, we walk through the exact MVP development process we use at ClickBoost Media: from concept validation and feature prioritization to wireframing, development sprints, and launch strategy. We'll use our own FlexDay gym booking app as a case study, showing how focused scope, user interviews, prototype testing, analytics planning, and disciplined release cycles helped shape a cleaner product while avoiding unnecessary spend and slow development detours.", "7 min read"],
  ["Content", "Content Marketing ROI: How to Measure What Actually Matters", "Every marketing director wants to know: 'Is our content actually working?' But most content ROI calculations are either too simplistic (just counting page views) or too complex to execute consistently. After 15 years of content marketing for B2B and B2C clients, we've developed a measurement framework that captures both the quantitative and qualitative value of content investments. This article covers the 7 metrics that genuinely predict content marketing ROI, how to set up proper attribution in Google Analytics 4, and the reporting structure we use with our clients. You'll learn how to connect content to pipeline, assisted conversions, sales enablement, ranking growth, lead quality, retention, and brand trust without creating a dashboard nobody uses.", "6 min read"],
  ["SEO", "Local SEO for Businesses Targeting Multicultural Communities Across US Cities", "The South Asian, Latin American, and East Asian communities represent some of the highest-income, most digitally engaged demographic groups in the United States — with significant concentrations in cities like Houston, Dallas, Chicago, New York, San Jose, and Atlanta. For businesses that serve or want to reach these communities, local SEO offers extraordinary targeting precision. In this guide, we cover the keyword research approach for culturally nuanced intent, Google Business Profile optimization tactics that build trust in tight-knit community markets, and the citation-building strategy that works for community-oriented businesses. We also explain how to balance neighborhood-specific landing pages, review generation, multilingual signals, culturally aware content, and local authority building without sacrificing broad-market visibility.", "9 min read"],
  ["SMO", "The ClickBoost Guide to Winning on LinkedIn for B2B Businesses in 2025", "LinkedIn has quietly become the highest-converting social platform for B2B lead generation — surpassing cold email and outbound calling for many industries. But most businesses are using it wrong: they post company updates nobody reads, run InMail campaigns with 2% response rates, and wonder why their investment isn't paying off. This guide covers the LinkedIn strategy we've used to generate qualified B2B leads for our US and Canadian clients, including the content types with the highest organic reach, the profile optimization checklist, and the outreach sequences that consistently book calls. You'll learn how to combine founder-led content, proof assets, targeted comments, relationship-building messages, and retargeting to create a reliable B2B pipeline.", "8 min read"],
];

const appCards = [
  ["RecallNotes", "iOS & Android", "Productivity", "A smart note-saving app that uses AI to tag, categorize, and surface your notes at the right moment. RecallNotes learns your patterns and reminds you of ideas before you need them — not after you've forgotten. Features voice capture, web clipper, and cross-device sync.", "Live", "🧠"],
  ["FlexDay — Local Gym Booking", "iOS & Android & Web", "Health & Fitness", "Walk into any gym, any day. FlexDay lets users discover and book single-day gym passes at partner fitness centers nearby — no memberships, no commitments. Perfect for travelers, casual gym-goers, and people who want variety in their workout locations.", "Live", "💪"],
  ["Sparks — Dating App", "iOS & Android", "Social / Dating", "A values-first dating app designed for meaningful connections. Sparks uses compatibility profiling, shared interest matching, and conversation starters to help people connect beyond just photos. Includes video introductions and interest-based group discovery.", "Beta", "💫"],
  ["SiteScout — SEO Audit App", "Web & iOS", "Marketing / SEO Tools", "An on-the-go SEO audit tool for marketers and business owners. Enter any URL and get an instant audit report covering page speed, meta tag health, mobile-friendliness, backlink snapshot, keyword density, and Core Web Vitals. Ideal for quick client pitches and self-audits.", "Live", "🔎"],
  ["LocalEats — Restaurant Discovery", "iOS & Android", "Food & Lifestyle", "Hyperlocal restaurant discovery app focused on authentic, independent eateries. LocalEats uses community reviews, cuisine filters, dietary preferences, and crowd-sourced 'hidden gem' nominations to help food lovers find the best spots off the beaten path.", "Demo Available", "🍽️"],
  ["TradeTrack — Freelancer Invoice & Time App", "Web & iOS", "Business / Productivity", "A lightweight invoicing and time-tracking app for freelancers and independent contractors. Create professional invoices in 30 seconds, track billable hours by project, and get paid faster with integrated payment links. Designed for solo operators who hate admin work.", "Live", "⏱️"],
];

const regionData = {
  "United States": [
    ["Austin, TX", "Austin's tech boom has created one of the most competitive digital landscapes in the US. With a rapidly growing South Asian tech community in Round Rock and North Austin, businesses here value data-driven digital partnerships. Strong demand for SaaS marketing, tech startup SEO, and B2B content."],
    ["Boston, MA", "Home to world-class universities and a thriving biotech and education sector, Boston also hosts a significant South Asian student and professional community in Cambridge and Somerville. High demand for academic institution marketing, healthcare SEO, and professional services content."],
    ["Charlotte, NC", "Charlotte's financial services sector and rapid population growth make it one of the most active markets for local SEO and real estate marketing. Growing South Asian community in Ballantyne and South Charlotte creates strong opportunity for culturally aware campaigns."],
    ["Chicago, IL", "A dense, competitive market with strong demand across every vertical. Chicago's South Asian community along the Devon Avenue corridor is large and economically active, creating high opportunity for restaurant marketing, legal firm SEO, and retail e-commerce."],
    ["Columbus, OH", "Columbus is an emerging tech hub with a large university-linked South Asian professional population. The startup ecosystem is growing quickly, increasing demand for performance-driven digital marketing."],
    ["Dallas, TX", "Dallas has one of the largest South Asian communities in the US, concentrated in Plano, Irving, and Frisco. Dallas businesses value performance-oriented, data-driven marketing with transparent reporting."],
    ["Denver, CO", "Denver is a fast-growing lifestyle market with a sophisticated consumer base. Its multicultural professional community is growing rapidly, with strong demand for e-commerce, fitness app marketing, and outdoor brand SEO."],
    ["Houston, TX", "Houston has one of the largest and most economically diverse South Asian populations in the US. High demand spans law firm SEO, medical practice marketing, restaurant digital marketing, and real estate."],
    ["Indianapolis, IN", "Indianapolis offers a Midwestern market with lower digital competition, making it easier to achieve Page 1 results quickly. Its growing tech sector supports receptive professional communities across industries."],
    ["Jacksonville, FL", "Florida's largest city by area is experiencing rapid population growth and significant digital marketing needs. Real estate, healthcare, and hospitality brands can win with stronger local visibility."],
    ["Los Angeles, CA", "Los Angeles is one of the most competitive and diverse markets in the world. Its South Asian community in Artesia, Cerritos, and the San Fernando Valley creates opportunity across entertainment, e-commerce, real estate, and professional services."],
    ["Miami, FL", "Miami is a global business hub with strong demand for multilingual digital marketing. The market offers high opportunity in luxury real estate, hospitality, and international trade."],
    ["New York, NY", "New York is the largest market in the US, with a major South Asian community concentrated in Queens, the New Jersey corridor, and Edison. Intense competition across all verticals rewards experienced, disciplined digital strategy."],
    ["Philadelphia, PA", "Philadelphia is a major East Coast market with strong healthcare, education, and professional services sectors. South Asian professional communities across Bucks County and the Delaware Valley create added opportunity."],
    ["Phoenix, AZ", "Phoenix is one of the fastest-growing US cities. Multicultural tech professionals have relocated here in significant numbers, fueling real estate and home services marketing demand."],
    ["San Antonio, TX", "San Antonio has a competitive local business landscape and a growing multicultural business community. Local SEO and restaurant marketing are especially active opportunities."],
    ["San Diego, CA", "San Diego's economy is shaped by biotech, defense, and tourism. The South Asian professional community in the Sorrento Valley biotech corridor supports high demand for B2B tech marketing and healthcare SEO."],
    ["San Francisco / Bay Area, CA", "The Bay Area is a global epicenter of tech and innovation. Its influential South Asian community across Silicon Valley creates a premier market for SaaS marketing, startup SEO, product launch content, and LinkedIn B2B marketing."],
    ["Seattle, WA", "Seattle is home to Amazon, Microsoft, and hundreds of technology companies. Large South Asian professional communities in Bellevue, Redmond, and Kirkland make it a premier market for SaaS marketing, cloud services SEO, and B2B content."],
  ],
  Canada: [["Toronto, ON", "Canada's largest city and most multicultural metro area has strong demand across real estate, immigration consultancy, financial services, and e-commerce."], ["Vancouver, BC", "Vancouver is a Pacific gateway with strong multicultural presence and high demand for real estate marketing, hospitality, and immigration services."], ["Calgary, AB", "Calgary's oil, energy, tech, and professional services sectors create good demand for B2B marketing and professional services SEO."], ["Mississauga & Brampton, ON", "These vibrant commercial markets are among Canada's most diverse communities, creating excellent opportunity for local businesses and regional brands."]],
  "United Kingdom": [["London", "London's commercially active multicultural communities support strong demand across legal, financial, hospitality, and real estate sectors."], ["Birmingham", "The UK's second-largest city has high demand for local SEO, e-commerce, and restaurant or hospitality marketing."], ["Leicester", "Leicester is one of the UK's most diverse cities with a strong market for community-oriented businesses and cultural event marketing."], ["Manchester", "Manchester's tech sector and financial services market create strong demand for digital marketing support and B2B growth campaigns."]],
  "Middle East": [["Dubai, UAE", "Dubai's business environment demands cutting-edge digital marketing, with high opportunity across real estate, hospitality, retail, and B2B services."], ["Abu Dhabi, UAE", "Abu Dhabi's government and corporate sector supports demand for B2B marketing, corporate website development, and LinkedIn strategy."], ["Riyadh & Jeddah, Saudi Arabia", "Vision 2030 is transforming Saudi Arabia's digital economy, increasing demand for e-commerce, app development, and corporate digital marketing."], ["Doha, Qatar", "Doha's expat-driven economy spans hospitality, finance, and professional services, with growing demand in the post-World Cup expansion."]],
  India: [["Mumbai", "Mumbai's financial sector creates high demand for premium digital marketing, corporate website development, and financial services content."], ["Delhi / NCR", "Delhi / NCR is a massive metro market with strong B2B and D2C marketing demand across e-commerce, real estate, and education."], ["Bengaluru", "Bengaluru's SaaS companies, startups, and technology firms need world-class digital marketing to stand out in crowded categories."], ["Hyderabad", "Hyderabad's pharmaceutical and IT sectors create growing demand for B2B content and technical SEO."], ["Chennai", "Chennai's manufacturing, automotive, and IT ecosystem is well suited for technical B2B content and export-oriented marketing."]],
};

function orgSchema() {
  return {"@context":"https://schema.org","@type":"Organization","name":BRAND.name,"url":BRAND.site,"logo":`${BRAND.site}/logo.png`,"address":{"@type":"PostalAddress","streetAddress":BRAND.address,"addressLocality":"[City]","addressRegion":"[State]","postalCode":"[ZIP]","addressCountry":"US"},"contactPoint":{"@type":"ContactPoint","telephone":BRAND.phone,"contactType":"Customer Service","areaServed":["US","CA","GB","AE","IN"],"availableLanguage":"English"},"sameAs":["https://www.linkedin.com/company/clickboostmedia"]};
}
function localBusinessSchema(){return {"@context":"https://schema.org","@type":"LocalBusiness","name":BRAND.name,"image":`${BRAND.site}/og-image.jpg`,"url":BRAND.site,"telephone":BRAND.phone,"email":BRAND.email,"address":{"@type":"PostalAddress","streetAddress":BRAND.address,"addressLocality":"[City]","addressRegion":"[State]","postalCode":"[ZIP]","addressCountry":"US"},"areaServed":["US","CA","GB","AE","IN"]};}
function breadcrumbSchema(items){return {"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":items.map((item,i)=>({"@type":"ListItem",position:i+1,name:item.name,item:item.url}))};}
function faqSchema(faqs){return {"@context":"https://schema.org","@type":"FAQPage","mainEntity":faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))};}

function SEO({ title, description, slug = "", schemas = [] }) {
  const canonical = `${BRAND.site}/${slug}`.replace(/\/$/, slug ? "" : "/");
  useEffect(() => {
    document.title = `${title} | ClickBoost Media – Digital Marketing Agency`;
    const tags = [
      ["name", "description", description], ["name", "keywords", "digital marketing agency, SEO services USA, social media marketing, web development, content marketing agency"], ["name", "robots", "index, follow"],
      ["property", "og:title", `${title} | ClickBoost Media`], ["property", "og:description", description], ["property", "og:type", "website"], ["property", "og:url", canonical], ["property", "og:image", `${BRAND.site}/og-image.jpg`],
      ["name", "twitter:card", "summary_large_image"], ["name", "twitter:title", `${title} | ClickBoost Media`], ["name", "twitter:description", description],
    ];
    tags.forEach(([attr, key, content]) => {
      let el = document.head.querySelector(`meta[${attr}="${key}"]`);
      if (!el) { el = document.createElement("meta"); el.setAttribute(attr, key); document.head.appendChild(el); }
      el.setAttribute("content", content);
    });
    let can = document.head.querySelector('link[rel="canonical"]');
    if (!can) { can = document.createElement("link"); can.setAttribute("rel", "canonical"); document.head.appendChild(can); }
    can.setAttribute("href", canonical);
    document.head.querySelectorAll("script[data-schema]").forEach(s => s.remove());
    [orgSchema(), localBusinessSchema(), ...schemas].forEach((schema, i) => { const s = document.createElement("script"); s.type = "application/ld+json"; s.dataset.schema = String(i); s.textContent = JSON.stringify(schema); document.head.appendChild(s); });
  }, [title, description, canonical, schemas]);
  return null;
}

function Logo() { return <Link className="logo" to="/" aria-label="ClickBoost Media home"><span className="logo-mark">CB</span><span><strong>ClickBoost</strong><small>Media</small></span></Link>; }
function CTAButtons({ compact=false }) { return <div className={compact ? "cta-row compact" : "cta-row"}><a className="btn btn-primary" href={primaryCta}>📞 Book a Free Consultation Call</a><a className="btn btn-ghost" href={auditCta}>🔍 Get Your Free Website Audit</a></div>; }

function Navbar() {
  const [open,setOpen]=useState(false); const [scrolled,setScrolled]=useState(false); const { pathname }=useLocation();
  useEffect(()=>{setOpen(false); window.scrollTo(0,0)},[pathname]);
  useEffect(()=>{const on=()=>setScrolled(scrollY>20); on(); addEventListener("scroll",on,{passive:true}); return()=>removeEventListener("scroll",on);},[]);
  const nav=[ ["/","Home"],["/apps","Our Work / Apps"],["/#industries","Industries"],["/blog","Blog / Insights"],["/service-areas","Service Areas"],["/about","About Us"],["/contact","Contact"] ];
  return <header className={`site-header ${scrolled ? "solid" : ""}`}><nav className="nav-shell" aria-label="Main navigation"><Logo/><div className="desktop-nav"><div className="nav-item mega-parent"><Link to="/services/seo">Services</Link><div className="mega-menu">{services.map(s=><Link key={s.slug} to={`/services/${s.slug}`}><span>{s.icon}</span><strong>{s.nav}</strong><small>{s.overview}</small></Link>)}</div></div>{nav.map(([to,label])=><NavLink key={to} to={to}>{label}</NavLink>)}</div><div className="nav-ctas"><a className="btn btn-primary" href={primaryCta}>📞 Book Free Consultation</a><a className="btn btn-ghost" href={auditCta}>🔍 Free Website Audit</a></div><button className="hamburger" aria-label="Open mobile menu" aria-expanded={open} onClick={()=>setOpen(!open)}>☰</button></nav><div className={`mobile-drawer ${open ? "open" : ""}`}><Logo/>{[["/","Home"],...services.map(s=>[`/services/${s.slug}`,s.nav]),["/apps","Our Work / Apps"],["/#industries","Industries"],["/blog","Blog / Insights"],["/service-areas","Service Areas"],["/about","About Us"],["/contact","Contact"]].map(([to,label])=><Link key={to} to={to}>{label}</Link>)}<CTAButtons compact/></div></header>;
}

function Layout({children}) { const [top,setTop]=useState(false); useEffect(()=>{const on=()=>setTop(scrollY>300); addEventListener("scroll",on,{passive:true}); return()=>removeEventListener("scroll",on);},[]); return <><Navbar/><main>{children}</main><Footer/><a className="floating-call" href={primaryCta}>Book a Call</a><button className="chat-widget" aria-label="Live chat placeholder">💬 Live chat<br/><small>We're online</small></button><button className={`back-top ${top?"show":""}`} onClick={()=>scrollTo({top:0,behavior:"smooth"})} aria-label="Back to top">↑</button></>; }
function SectionTitle({eyebrow,title,sub,light=false}){return <div className={`section-title ${light?"light":""}`}><span>{eyebrow}</span><h2>{title}</h2>{sub&&<p>{sub}</p>}</div>}
function ContactNote(){return <p className="form-note">Prefer to call? Reach us at <a href={`tel:${BRAND.phone}`}>{BRAND.phone}</a></p>}
function SmartForm({children,subject="Website Inquiry",className="form-card"}){const [sent,setSent]=useState(false); return <form className={className} action={`mailto:${BRAND.email}?subject=${encodeURIComponent(subject)}`} method="post" encType="text/plain" onSubmit={()=>setSent(true)}>{children}{sent&&<div className="success" role="status">Thanks! We'll be in touch within 24 hours. For urgent inquiries, email us directly at {BRAND.email}</div>}<ContactNote/></form>}

function Home(){ const schemas=useMemo(()=>[{"@context":"https://schema.org","@type":"WebSite","url":BRAND.site,"name":BRAND.name,"potentialAction":{"@type":"SearchAction","target":`${BRAND.site}/search?q={search_term_string}`,"query-input":"required name=search_term_string"}}],[]); return <Layout><SEO title="Global Digital Marketing Agency" description="Premium digital marketing agency with SEO, social media, web development, apps, and content for measurable global growth." schemas={schemas}/><section className="hero"><div className="mesh"></div><div className="shape s1"></div><div className="shape s2"></div><div className="container hero-grid"><div className="hero-copy reveal"><span className="eyebrow">{BRAND.tagline}</span><h1>15 Years of Turning Clicks Into Clients — Globally</h1><p>We are ClickBoost Media — a dedicated team of SEO specialists, social media strategists, app developers, and content experts driving measurable growth for businesses across the US, Canada, UK, Middle East, and beyond.</p><div className="ticker"><span>🔴 LIVE:</span><b>847 keywords ranked on Page 1 this month</b><b>23 new backlinks acquired today</b><b>98% client satisfaction since 2009</b></div><div className="hero-actions"><a className="btn btn-primary" href={auditCta}>Get Free Website Audit</a><a className="btn btn-secondary" href="/about">▶ Watch Our Story</a></div></div><aside className="hero-panel reveal delay"><div className="panel-orbit">AI</div><h2>Growth Command Center</h2><p>SEO, paid media, content, social, web, and app intelligence in one accountable team.</p><div className="mini-metrics"><span><b>15+</b> Years</span><span><b>50+</b> Clients</span><span><b>98%</b> Satisfaction</span></div></aside></div><div className="trust-bar"><span>Trusted by businesses across</span><b>🇺🇸 US</b><b>🇨🇦 CA</b><b>🇬🇧 UK</b><b>🇦🇪 UAE</b><b>🇮🇳 IN</b></div></section><Stats/><Why/><ServicesOverview/><AISection/><Testimonials/><Industries/><AuditBanner/><BlogPreview/></Layout> }
function CountUp({value,suffix}){
  const [count,setCount]=useState(0);
  const [node,setNode]=useState(null);
  useEffect(()=>{
    if(!node) return;
    const obs=new IntersectionObserver(([entry])=>{
      if(!entry.isIntersecting) return;
      const start=performance.now();
      const duration=1400;
      const tick=(now)=>{
        const progress=Math.min((now-start)/duration,1);
        const eased=1-Math.pow(1-progress,3);
        setCount(Math.round(value*eased));
        if(progress<1) requestAnimationFrame(tick);
      };
      requestAnimationFrame(tick);
      obs.disconnect();
    },{threshold:.4});
    obs.observe(node);
    return()=>obs.disconnect();
  },[node,value]);
  return <strong ref={setNode} data-count={value}>{count.toLocaleString()}{suffix}</strong>;
}
function Stats(){const data=[[15,"Years of Experience","+"],[50,"Clients Served Globally","+"],[98,"Client Satisfaction Rate","%"],[5,"Core Service Disciplines",""],[1200,"Keywords Ranked Page 1","+"]]; return <section className="stats section"><div className="container stats-grid">{data.map(([n,l,s])=><div className="stat-card reveal" key={l}><CountUp value={n} suffix={s}/><span>{l}</span></div>)}</div></section>}
function Why(){return <section className="section"><div className="container"><SectionTitle eyebrow="Why ClickBoost?" title="We Don't Just Understand Marketing. We Understand People."/><div className="three-grid">{[["Customer Psychology Experts","Every campaign we build starts with understanding human behavior. We study your target audience's motivations, pain points, and decision triggers — not just their demographics. This psychological foundation is why our campaigns convert where others just generate impressions.","🧭"],["Technology That Moves With the Market","From classic SEO to AI-powered generative engine optimization (GEO), from Facebook Ads to performance-max campaigns, we stay ahead of every platform shift. When Google changes its algorithm, we're ready. When AI reshapes search, we're already optimizing for it.","⚡"],["A Dedicated Team. Exceptional Value.","We run lean and invest in talent — not overhead. Every client works directly with senior specialists across SEO, content, development, and social. You get enterprise-grade strategy with the responsiveness of a boutique agency that genuinely cares about your results.","🤝"]].map(c=><article className="feature-card reveal" key={c[0]}><span className="icon-bubble">{c[2]}</span><h3>{c[0]}</h3><p>{c[1]}</p></article>)}</div></div></section>}
function ServicesOverview(){return <section className="section soft"><div className="container"><SectionTitle eyebrow="Services" title="Everything You Need. One Accountable Team." sub="Dedicated professionals in each discipline — no generalists, no finger-pointing."/><div className="service-grid">{[...services,{slug:"ppc",nav:"PPC & Paid Advertising",icon:"◎",overview:"Google Ads, Meta Ads, LinkedIn Ads, retargeting"}].map(s=><article className="service-card reveal" key={s.slug}><span>{s.icon}</span><h3>{s.nav}</h3><p>{s.overview}</p><Link to={s.slug==='ppc'?'/contact':`/services/${s.slug}`}>Learn More →</Link></article>)}</div></div></section>}
function AISection(){return <section className="section ai-section"><svg className="neural" viewBox="0 0 800 260" role="img" aria-label="Glowing neural network marketing animation"><path d="M40 140 C180 10, 260 250, 410 120 S650 20, 760 160"/><circle cx="40" cy="140" r="8"/><circle cx="250" cy="90" r="8"/><circle cx="410" cy="120" r="8"/><circle cx="610" cy="80" r="8"/><circle cx="760" cy="160" r="8"/></svg><div className="container"><SectionTitle light eyebrow="AI Marketing" title="Marketing in the Age of AI — We're Already There"/><div className="three-grid">{[["AI Content Optimization","We use AI analysis to identify content gaps your competitors haven't found, then fill them with content that ranks in both traditional search and AI-generated answers (ChatGPT, Perplexity, Google SGE)."],["Predictive Campaign Intelligence","Our data models analyze historical performance patterns to predict which ad creatives, targeting segments, and bid strategies will outperform — before we spend your budget."],["Answer Engine Optimization (AEO)","As AI chatbots become a primary discovery channel, we optimize your brand to appear in AI-generated answers — the new 'position zero' of the AI era."]].map(x=><article className="dark-card reveal" key={x[0]}><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></div></section>}
function Testimonials(){const t=[['ClickBoost took our Houston law firm from page 5 to page 1 for 12 competitive keywords in under 4 months. The ROI has been extraordinary.','Sarah Mitchell, CEO, Horizon Law Group, Houston TX','🇺🇸'],['Their SMO team understands US social media culture perfectly — our engagement tripled and we have closed 6 new enterprise clients from LinkedIn alone.','Mark Ellison, Founder, Northstar SaaS, Seattle WA','🇺🇸'],['The app they built for us is cleaner and faster than anything we were quoted locally — and the communication has been seamless from day one.','Emma Collins, Product Lead, FitPass Studio, Toronto ON','🇨🇦'],['We have worked with three other agencies before ClickBoost. None matched the transparency, speed, or results we get from this team.','James Whitmore, Director, Finch Retail Group, London','🇬🇧']]; return <section className="section"><div className="container"><SectionTitle eyebrow="Testimonials" title="What Our Clients Say"/><div className="testimonial-track">{[...t,...t].map((x,i)=><article className="testimonial" key={i}><div className="stars">★★★★★</div><p>“{x[0]}”</p><strong>{x[1]}</strong><span>{x[2]}</span></article>)}</div></div></section>}
function Industries(){const inds=['Law Firms','Healthcare','Real Estate','E-Commerce','Restaurants','SaaS / Tech','Financial Services','Education','Hospitality','Fitness & Wellness','Construction','Automotive','Immigration Consultants','Retail']; return <section id="industries" className="section soft"><div className="container"><SectionTitle eyebrow="Industries" title="Built for High-Competition Markets"/><div className="chips">{inds.map(i=><span key={i}>{i}</span>)}</div></div></section>}
function AuditBanner(){return <section className="section"><div className="container"><div className="audit-banner"><div><h2>Is Your Website Leaving Money on the Table?</h2><p>Get a free, no-obligation website audit — we'll analyze your SEO health, page speed, on-page optimization, backlink profile, and competitor gaps. Delivered within 48 hours.</p></div><SmartForm subject="Free Website Audit Request" className="audit-form"><label>Name<input name="Name" required/></label><label>Email<input name="Email" type="email" required/></label><label>Website URL<input name="Website" type="url" required/></label><label>Phone (optional)<input name="Phone"/></label><button className="btn btn-primary" type="submit">Send My Free Audit →</button></SmartForm></div></div></section>}
function BlogPreview(){return <section className="section soft"><div className="container"><SectionTitle eyebrow="Insights" title="Latest Thinking From ClickBoost"/><div className="blog-grid">{blogPosts.slice(0,3).map(p=><BlogCard key={p[1]} post={p}/>)}</div></div></section>}
function BlogCard({post,large=false}){return <article className={`blog-card reveal ${large?'featured':''}`} data-cat={post[0]}><span className="pill">{post[0]}</span><h2>{post[1]}</h2><p>{post[2]}</p><div className="author"><span className="avatar" aria-hidden="true">CB</span><small>ClickBoost Strategy Team • June 02, 2026 • {post[3]}</small></div><a href={`mailto:${BRAND.email}?subject=Article Inquiry: ${encodeURIComponent(post[1])}`}>Read Article →</a></article>}

function ServicePage({service}){
  const schemas=useMemo(()=>[breadcrumbSchema([{name:"Home",url:BRAND.site},{name:service.nav,url:`${BRAND.site}/services/${service.slug}`}]),faqSchema(service.faqs)], [service]);
  return <Layout>
    <SEO title={service.nav} description={service.desc} slug={`services/${service.slug}`} schemas={schemas}/>
    <PageHero eyebrow="Services" title={service.title} sub={service.desc}/>
    <section className="section"><div className="container narrow"><p className="lead">{service.intro}</p></div></section>
    <section className="section soft"><div className="container"><SectionTitle eyebrow="Included" title="What's Included"/><div className="check-grid">{service.included.map(i=><div className="check" key={i}>✓ {i}</div>)}</div></div></section>
    <section className="section"><div className="container"><SectionTitle eyebrow="Process" title="Our Process"/><div className="process">{service.process.map((p,i)=><div key={p}><span>{i+1}</span><strong>{p}</strong></div>)}</div></div></section>
    <section className="section soft"><div className="container two-col"><div><h2>Why Choose ClickBoost for {service.short}?</h2><p>Every engagement is led by dedicated specialists with senior oversight, transparent reporting, and a measurable growth plan. We do not hide behind jargon or vanity metrics. We clarify the business goal, build the right execution system, and keep improving until the results compound.</p></div><div><h2>Technologies & Tools We Use</h2><div className="chips">{service.tools.map(t=><span key={t}>{t}</span>)}</div>{service.slug==='app-development'&&<Link className="text-link" to="/apps">See our demo apps below →</Link>}</div></div></section>
    <FAQ faqs={service.faqs}/><BottomCTA/>
  </Layout>
}
function PageHero({eyebrow,title,sub}){return <section className="page-hero"><div className="container"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1>{sub&&<p>{sub}</p>}<CTAButtons/></div></section>}
function FAQ({faqs}){return <section className="section"><div className="container narrow"><SectionTitle eyebrow="FAQ" title="Questions We Hear Often"/>{faqs.map(([q,a])=><details className="faq" key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>}
function BottomCTA(){return <section className="section"><div className="container"><div className="bottom-cta"><h2>Ready to Turn Marketing Into Measurable Growth?</h2><p>Talk with a dedicated strategist and get a practical plan for your next 90 days.</p><CTAButtons/></div></div></section>}

function Apps(){return <Layout><SEO title="Our Apps" description="Explore demo applications built by ClickBoost Media across productivity, fitness, dating, SEO tools, lifestyle, and business." slug="apps" schemas={[breadcrumbSchema([{name:"Home",url:BRAND.site},{name:"Our Apps",url:`${BRAND.site}/apps`}])]}/><PageHero eyebrow="Our Work / Apps" title="Apps We've Built — Real Products, Real Users" sub="Our application development team has shipped multiple live products across productivity, fitness, lifestyle, and marketing. Here's a look at what we've built."/><section className="section"><div className="container app-grid">{appCards.map(a=><article className="app-card reveal" key={a[0]}><div className="app-icon" role="img" aria-label={`${a[0]} app icon placeholder`}>{a[5]}</div><span className="pill">{a[2]}</span><h2>{a[0]}</h2><div className="badges">{a[1].split(' & ').map(b=><b key={b}>{b}</b>)}</div><p>{a[3]}</p><em>{a[4]}</em><a className="btn btn-ghost" href={`mailto:${BRAND.email}?subject=Case Study Request: ${encodeURIComponent(a[0])}`}>View Case Study</a></article>)}</div></section><section className="section"><div className="container"><div className="bottom-cta"><h2>Have an App Idea? Let's Build It.</h2><p>From wireframe to App Store submission — our development team handles it all. Tell us your idea and we'll give you a free feasibility assessment.</p><a className="btn btn-primary" href={`mailto:${BRAND.email}?subject=App Development Inquiry`}>Book a Free App Consultation →</a><ContactNote/></div></div></section></Layout>}
function Blog(){const [cat,setCat]=useState('All'); const cats=['All','SEO','SMO','Web Dev','App Dev','Content','AI Marketing']; const shown=cat==='All'?blogPosts:blogPosts.filter(p=>p[0]===cat); return <Layout><SEO title="Blog and Insights" description="Digital marketing insights on SEO, social media, AI marketing, web development, app development, and content strategy." slug="blog" schemas={[breadcrumbSchema([{name:"Home",url:BRAND.site},{name:"Blog",url:`${BRAND.site}/blog`}])]}/><PageHero eyebrow="Blog / Insights" title="Insights & Strategies for Modern Digital Marketing" sub="Expert perspectives on SEO, social media, technology, and growth marketing — from practitioners who do this every day."/><section className="section"><div className="container"><BlogCard post={blogPosts[0]} large/><div className="filters" role="tablist">{cats.map(c=><button key={c} className={cat===c?'active':''} onClick={()=>setCat(c)}>{c}</button>)}</div><div className="blog-grid">{shown.map(p=><BlogCard key={p[1]} post={p}/>)}</div></div></section><section className="section soft"><div className="container narrow"><div className="newsletter"><h2>Get Weekly Insights Delivered to Your Inbox</h2><SmartForm subject="Newsletter Signup"><label>Name<input name="Name" required/></label><label>Email<input type="email" name="Email" required/></label><button className="btn btn-primary" type="submit">Subscribe →</button></SmartForm></div></div></section></Layout>}
function ServiceAreas(){const [region,setRegion]=useState('United States'); return <Layout><SEO title="Service Areas" description="Digital marketing services for businesses across US, Canada, UK, Middle East, and India with region-aware growth strategies." slug="service-areas" schemas={[breadcrumbSchema([{name:"Home",url:BRAND.site},{name:"Service Areas",url:`${BRAND.site}/service-areas`}])]}/><PageHero eyebrow="Service Areas" title="Digital Marketing Services — Wherever Your Business Operates" sub="We serve clients across 5 regions with strategies tailored to local markets, cultural nuances, and regional competition dynamics."/><section className="section"><div className="container"><div className="tabs" role="tablist">{Object.keys(regionData).map(r=><button key={r} className={region===r?'active':''} onClick={()=>setRegion(r)}>{r}</button>)}</div><div className="areas-grid">{regionData[region].map(([city,copy])=><article className="area-card reveal" key={city}><h3>{city}</h3><p>{copy}</p><p><strong>Services available:</strong> SEO, SMO, Web Development, Application Development, Content Marketing, PPC.</p><a className="btn btn-ghost" href={`mailto:${BRAND.email}?subject=Inquiry from ${encodeURIComponent(city)}`}>Get a Free Quote for {city}</a></article>)}</div></div></section></Layout>}
function Contact(){const faqs=[['What time zones do you work with?','Our team accommodates EST, CST, PST, and GMT schedules with ease.'],["What's your minimum engagement?",'We work with monthly retainers — contact us for a custom quote tailored to your goals.'],['How do you communicate with clients?','Slack, Email, WhatsApp, Zoom/Google Meet — whatever you prefer.'],['Do you sign NDAs?','Absolutely. We sign NDAs before any project discussion upon request.'],['How quickly can we get started?','Most clients are onboarded within 5–7 business days of signing.']]; return <Layout><SEO title="Contact" description="Contact ClickBoost Media for SEO, social media, web development, app development, content marketing, and PPC growth support." slug="contact" schemas={[breadcrumbSchema([{name:"Home",url:BRAND.site},{name:"Contact",url:`${BRAND.site}/contact`}]),faqSchema(faqs)]}/><PageHero eyebrow="Contact" title="Let's Build Something Great Together" sub="Whether you're ready to start a project or just exploring your options — reach out. We respond within 24 hours."/><section className="section"><div className="container contact-grid"><SmartForm subject="New Inquiry from Website"><label>Full Name*<input name="Full Name" required/></label><label>Company Name<input name="Company"/></label><label>Email*<input name="Email" type="email" required/></label><label>Phone<input name="Phone"/></label><label>Country/Region<select name="Country"><option>United States</option><option>Canada</option><option>United Kingdom</option><option>Middle East</option><option>India</option><option>Other</option></select></label><label>Service Interested In<select name="Service"><option>SEO</option><option>SMO</option><option>Web Dev</option><option>App Dev</option><option>Content Marketing</option><option>PPC</option><option>All-in-One Package</option></select></label><label>Message*<textarea name="Message" required></textarea></label><label>How did you hear about us?<input name="Referral"/></label><label>📎 Attach your brief (optional)<input type="file" name="Brief"/></label><button className="btn btn-primary" type="submit">Send Message →</button></SmartForm><aside className="contact-card"><h2>Contact Details</h2><p>📧 <a href={`mailto:${BRAND.email}`}>{BRAND.email}</a></p><p>📞 <a href={`tel:${BRAND.phone}`}>{BRAND.phone}</a></p><p>📍 {BRAND.address}</p><p>🕐 Business Hours: Mon–Fri, 9AM–6PM EST</p><CTAButtons/></aside></div></section><FAQ faqs={faqs}/></Layout>}
function About(){return <Layout><SEO title="About Us" description="Learn about ClickBoost Media, a global digital marketing agency with 15+ years, 50+ clients, and 98% satisfaction." slug="about" schemas={[breadcrumbSchema([{name:"Home",url:BRAND.site},{name:"About",url:`${BRAND.site}/about`}])]}/><PageHero eyebrow="About Us" title="15 Years. 50+ Clients. One Obsession: Your Growth." sub={BRAND.subTagline}/><section className="section"><div className="container two-col"><article><h2>Our Story</h2><p>Founded over 15 years ago with a single goal — to build a digital marketing agency that combined strategic depth with genuine accountability. We've grown from a small specialist team into a full-service operation with dedicated professionals across SEO, social media, application development, web development, and content marketing. What hasn't changed is our belief that great marketing is part psychology, part data, part creativity — and entirely about delivering results that matter to your business.</p></article><article><h2>Our Mission</h2><p>To be the most trusted digital growth partner for ambitious businesses — delivering enterprise-grade strategy, transparent reporting, and measurable results, with the personal accountability that large agencies can't match.</p></article></div></section><section className="section soft"><div className="container"><SectionTitle eyebrow="Team" title="A Globally Distributed Team of Specialists"/><div className="service-grid">{['SEO Team','Social Media Team','Development Team','Content Team','Strategy & Analytics Team'].map((x,i)=><article className="service-card" key={x}><span>{['⌁','◍','▣','✦','◎'][i]}</span><h3>{x}</h3><p>Dedicated senior specialists focused on accountable execution and clear communication.</p></article>)}</div></div></section><section className="section"><div className="container"><SectionTitle eyebrow="Values" title="How We Work"/><div className="chips big">{['Transparency','Results-Obsession','Cultural Intelligence','Technical Excellence','Client-First Thinking'].map(v=><span key={v}>{v}</span>)}</div><div className="awards">{['Top Digital Marketing Agency 2024','Google Partner Certified','Clutch Top Agency','98% Client Satisfaction Rate'].map(a=><b key={a}>{a}</b>)}</div><div className="timeline">{[['2009','Founded with a specialist growth mandate'],['2014','Expanded into web and content systems'],['2019','Launched application development practice'],['2024','Reached 98% client satisfaction benchmark'],['2026','Optimizing brands for AI-powered discovery']].map(x=><div key={x[0]}><strong>{x[0]}</strong><p>{x[1]}</p></div>)}</div></div></section></Layout>}
function Footer(){return <footer className="footer"><div className="container footer-grid"><div><Logo/><p>{BRAND.tagline}</p><div className="socials"><a aria-label="LinkedIn" href="https://www.linkedin.com/company/clickboostmedia">in</a><a aria-label="Instagram" href="/">ig</a><a aria-label="Facebook" href="/">fb</a><a aria-label="Twitter/X" href="/">x</a><a aria-label="YouTube" href="/">yt</a></div><small>© 2024 ClickBoost Media. All Rights Reserved.</small></div><FooterList title="Services" items={['SEO Services','Social Media Marketing','Web Development','App Development','Content Marketing','PPC & Paid Ads']}/><FooterList title="Company" items={['About Us','Our Apps','Blog / Insights','Careers','Privacy Policy','Terms of Service']}/><div><h3>Service Areas (US)</h3><p>Austin • Boston • Chicago • Dallas • Houston • Los Angeles • Miami • New York • San Francisco • Seattle • Philadelphia • Phoenix</p></div><div><h3>Contact</h3><p>{BRAND.email}<br/>{BRAND.phone}<br/>{BRAND.address}</p><CTAButtons compact/></div></div><div className="footer-bottom">ClickBoost Media — Digital Marketing Agency | Serving clients across the US, Canada, UK, Middle East, and India | Google Partner | Trusted Since 2009</div></footer>}
function FooterList({title,items}){return <div><h3>{title}</h3>{items.map(i=><a key={i} href={i.includes('SEO')?'/services/seo':i.includes('Social')?'/services/smo':i.includes('Web')?'/services/web-development':i.includes('App')?'/services/app-development':i.includes('Content')?'/services/content-marketing':i.includes('About')?'/about':i.includes('Apps')?'/apps':i.includes('Blog')?'/blog':'/contact'}>{i}</a>)}</div>}

export default function App(){return <Routes><Route path="/" element={<Home/>}/>{services.map(s=><Route key={s.slug} path={`/services/${s.slug}`} element={<ServicePage service={s}/>}/>) }<Route path="/apps" element={<Apps/>}/><Route path="/blog" element={<Blog/>}/><Route path="/service-areas" element={<ServiceAreas/>}/><Route path="/about" element={<About/>}/><Route path="/contact" element={<Contact/>}/><Route path="*" element={<Home/>}/></Routes>}
